Update translations
alefragnani/vscode-bookmarks pull request #367
Opened 2021-01-03 16:08 UTC by loniceras

Hi. Some new translations have been made in this PR.

2021-01-07 00:10 UTC, alefragnani requested changes
I've made some comments. Basically to replace the `n` named ids, to use something more meaningful.

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "contents": "%bookmarks.viewsWelcome.bookmarksExplorer.contents.1%",
Avoid using `n` on ids. Use something meaningful, maybe based on the `when` clause, like `contents.whenEmpty`

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "contents": "%bookmarks.viewsWelcome.bookmarksExplorer.contents.2%",
Avoid using `n` on ids. Use something meaningful, maybe based on the `when` clause, like `contents.whenNoFileOpen`

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "contents": "%bookmarks.viewsWelcome.bookmarksExplorer.contents.3%",
Avoid using `n` on ids. Use something meaningful, maybe based on the `when` clause, like `contents.whenHasFileOpen`

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead.

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.2%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks.selection%` instead.

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.2%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks.selection%` instead.

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.2%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks.selection%` instead.

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.2%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks.selection%` instead.

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                "category": "%bookmarks.commands.category.1%"
Avoid using `n` on ids. Use `%bookmarks.commands.category.bookmarks%` instead

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                        "%bookmarks.configuration.multicursor.toggleMode.enumDescriptions.2%"
Avoid using `n` on ids. Use something meaningful for each item.

2021-01-07 00:10 UTC, alefragnani commented on package.json
> +                        "%bookmarks.configuration.label.suggestion.enumDescriptions.4%"
Avoid using `n` on ids. Use something meaningful for each item.

2021-01-07 00:10 UTC, alefragnani commented on package.nls.json
> +    "bookmarks.commands.category.2": "Bookmarks (Selection)",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.json
> +    "bookmarks.configuration.multicursor.toggleMode.enumDescriptions.2": "Literally toggles a bookmark in each line, instead of making all lines equals",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.json
> +    "bookmarks.configuration.label.suggestion.enumDescriptions.4": "Suggests the selected text (if available) or the entire line (when has no selection). You still need to confirm.",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.pt-br.json
> +    "bookmarks.viewsWelcome.bookmarksExplorer.contents.3": "No bookmarks yet.\nIn order to use Bookmarks, place the cursor in any location in the file and run the command:\n[Bookmarks: Toggle](comman
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.pt-br.json
> +    "bookmarks.commands.category.2": "Bookmarks (Seleção)",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.pt-br.json
> +    "bookmarks.configuration.multicursor.toggleMode.enumDescriptions.2": "Literally toggles a bookmark in each line, instead of making all lines equals",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.pt-br.json
> +    "bookmarks.configuration.label.suggestion.enumDescriptions.4": "Suggests the selected text (if available) or the entire line (when has no selection). You still need to confirm.",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.pt-br.json
> +    "bookmarks.viewsWelcome.bookmarksExplorer.contents.2": "No bookmarks yet.\nIn order to use Bookmarks, you have to open a file in the editor.\n[Open a File](command:workbench.action.quickOpen)\nTo
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.ru.json
> +    "bookmarks.viewsWelcome.bookmarksExplorer.contents.2": "No bookmarks yet.\nIn order to use Bookmarks, you have to open a file in the editor.\n[Open a File](command:workbench.action.quickOpen)\nTo
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.ru.json
> +    "bookmarks.viewsWelcome.bookmarksExplorer.contents.3": "No bookmarks yet.\nIn order to use Bookmarks, place the cursor in any location in the file and run the command:\n[Bookmarks: Toggle](comman
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.ru.json
> +    "bookmarks.commands.category.2": "Закладки (Выделение)",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.ru.json
> +    "bookmarks.configuration.multicursor.toggleMode.enumDescriptions.2": "Literally toggles a bookmark in each line, instead of making all lines equals",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.ru.json
> +    "bookmarks.configuration.label.suggestion.enumDescriptions.4": "Suggests the selected text (if available) or the entire line (when has no selection). You still need to confirm.",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.zh-cn.json
> +    "bookmarks.viewsWelcome.bookmarksExplorer.contents.3": "目前无书签。\n为了使用书签，你需要将光标放在文件的任意位置，然后运行命令：\n[书签: 开关](command:bookmarks.toggle)\n可以[阅读文档](http://github.com/alefragnani/vscode-bookmarks/#bookma
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.zh-cn.json
> +    "bookmarks.commands.category.2": "书签（选择）",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.multicursor.toggleMode.enumDescriptions.2": "分别开关每一个选中的行的书签。",
Update the `n` ids to the new ids

2021-01-07 00:10 UTC, alefragnani commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.label.suggestion.enumDescriptions.4": "使用选择的文本或（无选择的文本时）使用整个行作为标签，需要额外的确认。",
Update the `n` ids to the new ids

2021-01-07 00:12 UTC, alefragnani commented
Hi @loniceras ,

First of all, thank your for your PR 👍 

I've made some comments. Basically because of some of the ids are using a `n` based pattern. Please, update to something more meaningful, for easier understanding.

Thank you

2021-01-07 10:33 UTC, loniceras commented
Hi! Thank you for your detailed comments. I'v made a revision based on these suggestions :)

2021-01-08 15:44 UTC, alefragnani commented
Thank you for the updates. 

Everything appears to be ok. I’m planning to test it this weekend, and should be available in the next release.

Thank you

2021-01-15 10:59 UTC, merged