Add option to disable "No more bookmarks" notification
alefragnani/vscode-bookmarks pull request #396
Opened 2021-02-24 13:06 UTC by zioroboco

Particularly when the `wrapNavigation` and `navigateThroughAllFiles` options are disabled, the "No more bookmarks" notification can come up very frequently, and can become distracting.

This adds a configuration option to disable that notification (defaulting to the existing behaviour).

Unfortunately I couldn't build the extension due to the submodule issue, but hopefully it's a simple enough change.

Thanks!

2021-03-06 18:00 UTC, alefragnani commented
Hi @zioroboco ,

First of all, sorry for taking so long to answer you. It’s been a busy period.

About your PR, It’s a great addition. I have added a similar feature on my other [Numbered Bookmarks](https://github.com/alefragnani/vscode-numbered-bookmarks) extension, so I think it would use a similar naming convention.

Instead of a _generic_ `showNotifications` name, the setting could be more specific, like `showNoMoreBoomarksWarning`.

Please, update the PR so I could test/merge for the next release.

Thank you

2021-03-06 18:01 UTC, alefragnani requested changes

2021-03-06 18:01 UTC, alefragnani commented on package.json
> +                "bookmarks.showNotifications": {
Use a less generic name, like `showNoMoreBoomarksWarning`

2021-03-08 01:43 UTC, zioroboco commented
Hi @alefragnani — I've updated the PR with your suggestion. Thanks again!

2021-03-18 01:09 UTC, alefragnani approved these changes

2021-04-06 23:44 UTC, merged