Update zh-cn i18n
alefragnani/vscode-bookmarks pull request #707
Opened 2024-03-28 05:20 UTC by GreyElaina

2024-03-28 05:27 UTC, GreyElaina reviewed
This translated text strives to make the description consistent with the actual performance. If possible, please help me confirm it through Google Translator or other methods.

2024-03-28 09:24 UTC, GreyElaina commented
walkthrough might need wait for a moment, i'm busy for my life.

2024-03-29 03:30 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.commands.list.title": "列出当前文件中的书签",
```suggestion
    "bookmarks.commands.list.title": "书签列表",
```

2024-03-29 03:31 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.commands.clearFromFile.title": "删除当前文件中的所有书签",
```suggestion
    "bookmarks.commands.clearFromFile.title": "清空文件中所有书签",
```

2024-03-29 03:31 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.commands.clear.title": "删除所有书签",
```suggestion
    "bookmarks.commands.clear.title": "清空所有书签",
```

2024-03-29 03:32 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.commands.clearFromAllFiles.title": "清除所有书签",
```suggestion
    "bookmarks.commands.clearFromAllFiles.title": "清空所有书签",
```

2024-03-29 03:35 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.backgroundLineColor.description": "装饰器的背景色。使用 rgba() 并指定透明背景颜色，以与其他装饰一起使用。例如：rgba(21, 126, 251, 0.1)",
装饰器是什么鬼？

2024-03-29 03:38 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.showNoMoreBookmarksWarning.description": "在书签不存在时，是否在进行书签间导航时显示警告提示。",
```suggestion
    "bookmarks.configuration.showNoMoreBookmarksWarning.description": "在书签间导航时，当书签不存在，是否显示警告提示。",
```

2024-03-29 03:39 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.sidebar.expanded.description": "是否在书签侧边栏中以展开形式列出书签。",
建议在en环境下重新确认行为

2024-03-29 03:41 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.multicursor.toggleMode.enumDescriptions.eachLineIndependently": "分别对每一个选中的行添加或删除书签。",
```suggestion
    "bookmarks.configuration.multicursor.toggleMode.enumDescriptions.eachLineIndependently": "分别对选中的每一行行都添加或删除书签。",
```

2024-03-29 03:42 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.label.suggestion.enumDescriptions.dontUse": "禁用生成",
```suggestion
    "bookmarks.configuration.label.suggestion.enumDescriptions.dontUse": "不生成备注",
```

2024-03-29 03:43 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.label.suggestion.enumDescriptions.suggestWhenSelectedOrLineWhenNoSelected": "使用已选中的文本，且当无选中文本时使用整行上的内容，并需要额外的确认。",
```suggestion
    "bookmarks.configuration.label.suggestion.enumDescriptions.suggestWhenSelectedOrLineWhenNoSelected": "使用已选中的文本，或是当未选中任何文本时使用整行内容，并需要额外的确认。",
```

2024-03-29 03:45 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.revealLocation.description": "指定当跳转到书签位置时，书签所在行在编辑器中的定位位置",
```suggestion
    "bookmarks.configuration.revealLocation.description": "指定当跳转到书签位置时，书签所在行在编辑器中出现的位置",
```

2024-03-29 03:46 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.revealLocation.enumDescriptions.top": "将书签所在行定位到编辑器顶部",
```suggestion
    "bookmarks.configuration.revealLocation.enumDescriptions.top": "编辑器顶部",
```

2024-03-29 03:47 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.revealLocation.enumDescriptions.top": "将书签所在行定位到编辑器顶部",
```suggestion
    "bookmarks.configuration.revealLocation.enumDescriptions.top": "编辑器顶部",
```

2024-03-29 03:47 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.revealLocation.enumDescriptions.center": "将书签所在行定位到编辑器中心",
```suggestion
    "bookmarks.configuration.revealLocation.enumDescriptions.center": "编辑器中心",
```

2024-03-29 03:49 UTC, GreyElaina commented
enough good to me.

2024-03-31 07:12 UTC, GreyElaina commented on package.nls.zh-cn.json
> +    "bookmarks.commands.expandSelectionToPrevious.title": "扩展光标选取区域至上一个书签处",
```suggestion
    "bookmarks.commands.expandSelectionToNext.title": "扩展光标选区至下一个书签处",
    "bookmarks.commands.expandSelectionToPrevious.title": "扩展光标选区至上一个书签处",
```

2024-04-04 00:29 UTC, alefragnani requested changes

2024-04-04 00:29 UTC, alefragnani commented on package.nls.zh-cn.json
Hi @GreyElaina ,

First of all, thank you for your contribution.

About the updates, I don't know Chinese, so I can't comment about it. But, picking some random resources and using Google Translation to see the differences, I noticed a few that doesn't seem adequate, at least when translated to English/Portuguese, like `bookmarks.commands.toggle.title` and `bookmarks.views.Explorer.name`.

In this case, I would ask for help the original contributors of this file, like @axetroy , @loniceras e @huangyxi . If they don't find any issue, I would happily apply the changes.

BTW, I'm not sure you are aware of, but there is another other kind of resource for translations, if you are open to.

* walkthrough\someMarkdown.nls.XX.md files: walkthrough steps

Hope this helps.

2024-04-04 06:13 UTC, GreyElaina commented on package.nls.zh-cn.json
The previous translation looked like some kind of shoddy machine translation that didn't take the actual situation into account.

for example.

```
"bookmarks.commands.toggle.title": "开关",
"bookmarks.views.Explorer.name": "浏览器",
```

for me, it looks like:

```json5
"bookmarks.commands.toggle.title": "Switch",  // what switch, Nintendo Switch?
"bookmarks.views.Explorer.name": "Chrome",  // Yes exactly, VS Code really a Chrome LAMO.
```

(sorry for firefox/others users & nintendo)

Due to the lack of context and the lack of well-constructed paragraph, the previous translation was quite straightforward, as intimidating as if an Oxford Dictionary had been slapped on top.

In order to make your plug-in more consistent with the language habits of users of this language as much as possible, I had to rewrite part of the translation.

Direct translation is undoubtedly a disaster in this situation with an extreme lack of context.

2024-04-04 18:52 UTC, loniceras reviewed
Hi, @GreyElaina.

Thank you for your contribution to the these translations. I have read your modifications and I think most modifications are helpful in understanding the appropriate meaning.

But for some modifications, I think further revisions or elaborations are needed. I list some comments following:

- I admit that the original translation term `开关` of `toggle` is literal and strange. But it implies switching the status of the bookmark, so I did not modify this term. Though the new translation `添加 / 删除书签` will not cause ambiguity in most cases, this usage can be confusing in `bookmarks.configuration.multicursor.toggleMode.enumDescriptions.eachLineIndependently`. The translation `分别对选中的每一行都添加或删除书签。` does not tell us whether the actual behavior is to leave a bookmarked line unchanged or to delete the bookmark. If using the newly translated usage, I recommend using `如果选中行存在书签，则删除该书签；如果选中行不存在书签，则在该行添加书签。`.

- The translation `备注` of `label` in `bookmarks.commands.editLabel.title`, `bookmarks.commands.addLabeledBookmarkAtLine#gutter.title` and many other places doesn't seem to make the semantics any clearer. I suggest using `含标签的书签` instead of `标签书签` or `备注书签`. Other places can be modified similarly.

- The translation term `特别适配` of `workaround` in `bookmarks.configuration.useWorkaroundForFormatters.description`  doesn’t seem to be a standard term either. According to the translation from [China National Committee for Terminology in Science and Technology](https://www.termonline.cn/wordDetail?termName=%E7%BB%95%E8%BF%87%E6%93%8D%E4%BD%9C&subject=95416d1426b011ee888cb068e6519520&base=1), translation may be `绕过操作`. If combined with semantics, it seems that `适配方案` or original translation `解决方案` is more appropriate.

Apart from the above, I have no additional comments.

2024-04-05 05:02 UTC, GreyElaina commented
@loniceras LGTM.

2024-04-06 13:58 UTC, huangyxi reviewed
Thank you for inviting @alefragnani.

As a native Simplified Chinese user, I agree that some of the original AI translations may not be very interpretable for Chinese readers due to the lack of context. The new translations have addressed most of these issues, representing high-quality proofreading over the original version, thanks to @GreyElaina. However, as @loniceras has pointed out, some additional minor fixes may further improve the translation's understandability.

In my opinion, the following revisions could be considered:
- Consistently translating `Jump` as `跳转` in `bookmarks.commands.jumpToNext.title`, `bookmarks.commands.jumpToPrevious.title`, and `bookmarks.configuration.showCommandsInContextMenu.description`.
- I prefer not to append additional [Chengyu](https://en.wikipedia.org/wiki/Chengyu) (成语, Chinese idioms) in the translation to keep the documentation focused on content rather than literary elements, specifically `如臂使指` in `bookmarks.walkthroughs.navigateToBookmarks.description`. However, whether to amend it or not could be discussed later.

I hope these suggestions can help improve the translation quality. Thank you all for your contribution to the community!

2024-04-06 14:38 UTC, GreyElaina commented
Browsing the context here, i think that idioms can be appropriately used here to make the text more vivid and expressive. i believe the preceding text has already accurately described the essence and key points of this characteristic. Therefore, incorporating idioms at this point would add elegance to the text without sacrificing clarity.

Whatever, i would like to make this translation more elegant and semantic, so don't merge it for a while please!

2024-04-06 15:18 UTC, GreyElaina commented
leave the translation of walkground to posterity! this kind of translation does not seem to affect my daily use.

2024-04-06 16:51 UTC, GreyElaina commented
I read the implementation and fill up these translation, so it would not be same as the original texts (english ver.).

2024-04-07 02:09 UTC, huangyxi reviewed
- In a general comment not specific to newly updated code, I've reviewed the translation of the term `边缘标尺` or `gutter ruler`, where `gutter` has been translated as `装订线` in the official Chinese language pack of VS Code.
- This is my final attempt to maintain the translation style. I've noted your response regarding the Chengyu `如臂使指` and how literary elements can enhance the translation, which is also reasonable. However, I would like to reiterate one last time that the translation should adhere to the style of the original text. This consideration impacts the exclamatory mood in the latest modification `时刻准备着！`. But if you do insist on the style of translation, I'll respect your decision.

2024-04-07 02:28 UTC, axetroy commented on package.nls.zh-cn.json
> -    "bookmarks.views.Explorer.name": "浏览器",
Good catch!

2024-04-07 02:29 UTC, axetroy commented on package.nls.zh-cn.json
> -    "bookmarks.activitybar.title": "书签",
Could you please set the indent to 4 spaces as other files do this too.

And it can make changes to this file easier to review

2024-04-07 04:43 UTC, GreyElaina commented
> * In a general comment not specific to newly updated code, I've reviewed the translation of the term `边缘标尺` or `gutter ruler`, where `gutter` has been translated as `装订线` in the official Chinese language pack of VS Code.

LGTM.

> This is my final attempt to maintain the translation style. I've noted your response regarding the Chengyu 如臂使指 and how literary elements can enhance the translation, which is also reasonable. However, I would like to reiterate one last time that the translation should adhere to the style of the original text. This consideration impacts the exclamatory mood in the latest modification 时刻准备着！. But if you do insist on the style of translation, I'll respect your decision.

i deleted it.

2024-04-07 06:24 UTC, axetroy commented on package.nls.zh-cn.json
> +    "bookmarks.commands.toggleLabeled.title": "添加含标签的书签 / 删除书签",
In Chinese writing habits, spaces are not usually added before and after punctuation marks. Therefore, a more reasonable sentence is:

```suggestion
    "bookmarks.commands.toggleLabeled.title": "添加含标签的书签/删除书签",
```

2024-04-07 06:24 UTC, axetroy commented on package.nls.zh-cn.json
> +    "bookmarks.commands.jumpTo.title": "跳转至文档 / 行",
```suggestion
    "bookmarks.commands.jumpTo.title": "跳转至文档/行",
```

2024-04-07 06:24 UTC, axetroy commented on package.nls.zh-cn.json
> +    "bookmarks.commands.toggle.title": "添加 / 删除书签",
```suggestion
    "bookmarks.commands.toggle.title": "添加/删除书签",
```

2024-04-07 06:24 UTC, axetroy commented on package.nls.zh-cn.json
> +    "bookmarks.viewsWelcome.bookmarksExplorer.contents.whenHasFileOpen": "未找到任何书签。\n若需要添加书签，你需要先将光标放在文件的任意位置，然后运行命令：\n[书签: 添加 / 删除书签](command:bookmarks.toggle)\n可以通过[阅读文档](http://github.com/alefragna
```suggestion
    "bookmarks.viewsWelcome.bookmarksExplorer.contents.whenHasFileOpen": "未找到任何书签。\n若需要添加书签，你需要先将光标放在文件的任意位置，然后运行命令：\n[书签: 添加/删除书签](command:bookmarks.toggle)\n可以通过[阅读文档](http://github.com/alefragnani/vscode-bookmarks/#bookmarks)了解关于 VS Code 中使用书签的更多信息。",
```

2024-04-07 06:24 UTC, axetroy commented on package.nls.zh-cn.json
> +    "bookmarks.configuration.showCommandsInContextMenu.description": "是否在上下文菜单中显示书签命令（添加 / 删除书签、跳转至上一个 / 下一个书签）。",
```suggestion
    "bookmarks.configuration.showCommandsInContextMenu.description": "是否在上下文菜单中显示书签命令（添加/删除书签、跳转至上一个/下一个书签）。",
```

2024-04-07 06:28 UTC, axetroy commented
I don't see anything wrong with the rest, compared to the previous translation.

This is closer to the Chinese native language, rather than a rigid translation. Good Job, Elaina.

2024-04-07 06:56 UTC, GreyElaina commented
walkthough might need more review, i translate last night (it's so late!) and therefore it might lack some consider...

2024-04-07 07:19 UTC, GreyElaina commented
ok..please.

2024-04-07 09:00 UTC, axetroy reviewed
Everything look good to me 👍

2024-04-07 12:00 UTC, loniceras reviewed
I recommend the current translation now and hope these translations will be beneficial to the community. Thanks again to @GreyElaina and the other reviewers for their contributions again.

2024-04-08 10:49 UTC, alefragnani requested changes
Hi @GreyElaina ,

Fixing the filename should get the PR ready for merge.

Thank you

2024-04-08 10:49 UTC, alefragnani commented on l10n/bundle.I10n.zh-cn.json
Hi @GreyElaina ,

The file must be named _bundle.l10n.zh-cn.json_ (with an L - which referes to _localization_) instead of _i10n_. 

Thank you

2024-04-08 11:22 UTC, GreyElaina commented on l10n/bundle.I10n.zh-cn.json
done.

2024-04-08 13:49 UTC, huangyxi reviewed
LGTM

2024-04-08 21:14 UTC, merged